@api_HostAddress = http://localhost:5258/api

GET {{api_HostAddress}}/tasks

###
POST {{api_HostAddress}}/tasks
Content-Type: application/json

{
    "title": "New Task (1)",
    "description": "This is the first task",
    "status": "À faire",
    "user": {
        "firstName": "Sigmund",
        "lastName": "Freud"
    }
}

###
PATCH {{api_HostAddress}}/tasks/1
Content-Type: application/json

{
    "status": "En cours"
}